name: Deploy Application To Prod

on:
  workflow_dispatch:

jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ARTIFACT }}

    - name: Ensure Publish Directory Exists
      run: mkdir -p ./publish

    - name: Download from Blob Storage
      run: |
        az storage blob download \
          --name ${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip \
          --file ./publish/${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip \
          --account-name ${{ vars.AZURE_ARTIFACT_ACCOUNT_NAME }} \
          --container-name 'artifacts' \
          --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }}

    - name: Deploy to Azure Webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.PROD_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PROD_WEBAPP_PUBLISHPROFILE }}
        package: ./publish/${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip

    - name: Azure Logout
      uses: azure/CLI@v1
      with:
        inlineScript: az logout